language: node_js
node_js:
- lts/*
install:
- yarn install
script:
- yarn docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
env:
  global:
    secure: fI+EhJaioMpxSDkQi7GkfKe+irT0Yq0qrHDFNVJMmvP4wFsNyzwabkLHV4w5hjb8eRCTOCbSeh0l0bQ6XTSzitUP8xH7dKgg8j2jLE5UTgLopnCd0Cpw6ExJPVpwMs1j54Mo1U19CAUelMYVci/j9Y0MCjyj40SzYOoVeT+O3Plz1Y90qPE76B9HgltSjitNksYpVd9RugWgFHR8atbVMyzLpi+uct5gbV0rrVMrkQjrmoPe5pEu9oXDYoA5wyUslZlcH7V1rWIa28tlAGacj5Ig7g/26K1eoSChHEDOq2if/yKn69SelC0UFUZUZyyScK10XDaTChNLyzM9fc2IVifKMuDHz6N3EXtyMp+WoYz5RwruCRUWgnWNWagljfHhyt7oR69V4aLyCAurCpRyZEHs4y3MCXcmL6XRWKDKoSD2IjtCLY7ouOVcS9UkZ3Ut8ToApPNEXgpdIdtVnfo0Av+ElgUdQmxyu8KBH72dcNo1JBgmstGE/GAKtOacQOZa93ubMxVPCf5v8ho4vql78bEgAzvfollvCeQ0flm+3rmWeHDYp2IsRWpMYrPiynAjx9N2P5rzaMgJNQOWCpQrSnNyJH9a4B/BMsT1TPE/MIEoS0vRy2ymeVPDwbc5EGAgF3Zhw0dkBWB5Kl7/XsiSuvX0nYzuVdUUdFZsbvfYMXI=
